### ISSUE TITLE
`fbp-test` emits `graph/addedge` before `graph/addnode`.

### ISSUE THREAD

**Issue by Industrial** [flowbased/fbp-protocol#171]
Hi!

I'm trying to implement the FBP protocol by using `fbp-test` and implementing the required commands one by one.

What I have now is this:

```
--> {"protocol":"runtime","command":"getruntime","payload":{}}
<-- {"protocol":"runtime","command":"runtime","payload":{"id":"30a1eb22-a999-11ea-a909-93c8afee90c7","label":"deno-fbp","version":"0.1","type":"deno-fbp","capabilities":["network:control","network:data","network:persist","network:status","protocol:component","protocol:graph","protocol:network","protocol:runtime"]}}
--> {"protocol":"graph","command":"clear","payload":{"baseDir":"/home/tom/Code/code9/deno-fbp/test/node_modules/fbp-protocol","id":"foo","main":true,"name":"Foo graph"}}
<-- {"protocol":"graph","command":"clear","payload":{"id":"foo","main":false}}
--> {"protocol":"graph","command":"addedge","payload":{"src":{"node":"Repeat1","port":"out"},"tgt":{"node":"Drop1","port":"in"},"metadata":{"route":5},"graph":"foo"}}
graph.addEdge
graph.addEdge:graph {
  id: "foo",
  nodes: {},
  edges: {},
  initial: {},
  components: [],
  status: { running: false, started: false, debugging: false, startTime: null }
}
TypeError: Cannot read properties of undefined (reading 'ports')
    at addEdge (file:///home/tom/Code/code9/deno-fbp/src/domain/graph.ts:156:33)
    at addedge (file:///home/tom/Code/code9/deno-fbp/src/runtime/protocols/graph.ts:174:39)
    at WebSocketAcceptedClient.<anonymous> (file:///home/tom/Code/code9/deno-fbp/src/runtime/runtime.ts:51:35)
    at WebSocketAcceptedClient.emit (https://deno.land/std@0.92.0/node/events.ts:134:20)
    at WebSocketAcceptedClient.open (https://deno.land/x/websocket@v0.1.3/lib/websocket.ts:92:16)
```

As you can see `graph/addedge` is sent to the server but the graph has 0 nodes at this point.

1. Should I throw/return an Error event?
2. Shouldn't `fbp-test` send two `graph/addnode` events first, before connecting them? When connecting `Repeat1:out` to `in:Drop1` I do not know which components the nodes are so I can not create the nodes when the `graph/addedge` event happens.

**Comment by Industrial** [comment]
I've looked at the source a bit and saw this:

https://github.com/flowbased/fbp-protocol/blob/555880e1f42680bf45e104b8c25b97deff01f77e/src/WebSocket.js#L183

it seems like it __should__ call `graph/addnode` twice first but when I run the command it doesn't do that.

The project lives here: https://github.com/Industrial/deno-fbp

but it requires Deno and not Node.js :)
